"""Add PropertyImage model and update Property fields

Revision ID: 97b6f0cc2d6d
Revises: 446d5ba994bb
Create Date: 2025-04-01 23:28:40.897356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b6f0cc2d6d'
down_revision = '446d5ba994bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_image_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trulia_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathrooms', sa.Float(), nullable=True))
        batch_op.drop_column('buyer_name')
        batch_op.drop_column('seller_name')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('seller_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('buyer_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('bedrooms')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('trulia_url')

    with op.batch_alter_table('property_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_image_property_id'))

    op.drop_table('property_image')
    # ### end Alembic commands ###
